models:
  - name: acd
    data_folder: "C:/Users/m.zortea/Desktop/acd_map/acd"
    sensors:
      - "03056B18_x"
    flip_values: true
  - name: map
    data_folder: "C:/Users/m.zortea/Desktop/acd_map/map"
    sensors:
      - "03092809_z"
    flip_values: false
  - name: acd_2
    data_folder: "C:/Users/m.zortea/Desktop/acd_map/acd"
    sensors:
      - "03056B18_y"
    flip_values: false

chunk_time: 10min

analysis:
  time_visualization: false
  offset: true
  spectrum: false
  sine_fit: true
  relative_phases:
    - [map.03092809_z, acd.03056B18_x]
    - [acd.03056B18_x, map.03092809_z]
